server:
  port: 8000

spring:
  application:
    name: services-order

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: dev

  config:
    import:
      - nacos:service-order-common.properties?group=order
      - nacos:service-order-database.properties?group=order